[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM3
upload_speed = 115200
monitor_speed = 115200
lib_deps =
    chris--a/Keypad@^3.1.1
    madhephaestus/ESP32Servo@^3.0.5
    miguelbalboa/MFRC522@^1.4.11
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0